---
title: "Learning through gun violence"
format: html
---

```{r}
#| label: setup
#| include: false
set.seed(42L)
rlang::exec(
    knitr::opts_chunk$set,
    !!!hiRx::CHUNK_OPTIONS_FOR_KNITR,
    cache = TRUE
)
```

## Access local downloads

```{r}
#| label: identify-files
NIBRS_DIR <- hiRx::input_path("Downloads", "US Dept of Justice", "NIBRS")
ARCHIVE_FILES <- dir(NIBRS_DIR, full.names = TRUE)
```

```{r}
#| label: examine_contents
#| dependson:
#| - identify-files

TOC <- ARCHIVE_FILES |>
    rlang::set_names(
        basename(ARCHIVE_FILES)
    ) |>
    tibble::enframe(
        name = "File",
        value = "Contents"
    ) |>
    dplyr::mutate(
        State = stringr::str_extract(.data$File,
                                     "^.{2}"),
        Year = .data$File |>
            stringr::str_extract("\\d{4}") |>
            as.integer(),
        Contents = purrr::map(
            .data$Contents,
            zip::zip_list
        )
    )
```

## Actually use the data for research

### Incidents involving guns and violence

```{r}
#| label: load-violent-gun-crimes
#| dependson:
#| - examine-contents

GUNS <- dplyr::filter(
    nibrsr::GLOSSARY_OF_WEAPON_TYPES,
    stringr::str_detect(.data$weapon_code,
                        "^[12][1-5]A?")
)
    
VIOLENCE <- dplyr::filter(
    nibrsr::GLOSSARY_OF_OFFENSE_TYPES,
    .data$crime_against == "Person"
)

VIOLENT_GUN_CRIMES <- TOC |>
    dplyr::filter(
        stringr::str_detect(.data$File,
                            "^WI")
    ) |>
    purrr::pmap(
        \(File, Contents, ...) {
            .fn <- file.path(NIBRS_DIR,
                             File)
            .wpn <- .fn |>
                nibrsr::extract_incident_weapons(Contents) |>
                dplyr::semi_join(GUNS, by = "weapon_code")
            
            .off <- .fn |>
                nibrsr::extract_offenses(Contents) |>
                dplyr::semi_join(VIOLENCE, by = "offense_code") |>
                dplyr::semi_join(.wpn, by = "offense_id")
            
            .inc <- .fn |>
                nibrsr::extract_incidents(Contents) |>
                dplyr::semi_join(.off, by = "incident_id")
            
            .inc |>
                dplyr::left_join(
                    .off,
                    by = c("data_year", "incident_id")
                ) |>
                dplyr::left_join(
                    .wpn,
                    by = c("data_year", "offense_id")
                )
        }
    ) |>
    purrr::list_rbind()

VIOLENT_GUN_CRIMES |>
    dplyr::slice_sample(n = 10) |>
    knitr::kable()
```

```{r}
#| label: look-at-date-distributions
VIOLENT_GUN_CRIMES |>
    dplyr::inner_join(
        nibrsr::GLOSSARY_OF_OFFENSE_TYPES,
        by = "offense_code"
    ) |>
    dplyr::filter(
        !is.na(.data$incident_date)
    ) |>
    dplyr::mutate(
        Year = lubridate::year(.data$incident_date),
        Month = lubridate::month(.data$incident_date),
        Category = .data$offense_category_name
    ) |>
    dplyr::count(
        .data$incident_id,
        .data$Year,
        .data$Month,
        .data$Category
    ) |>
    dplyr::count(
        .data$Year,
        .data$Month,
        .data$Category,
        name = "Frequency"
    ) |>
    ggplot2::ggplot(
        ggplot2::aes(
            x = .data$Month,
            y = .data$Frequency,
            color = factor(.data$Year)
        )
    ) + 
    ggplot2::geom_line(
        linewidth = hiRx::PHI,
        lineend = "round",
        linejoin = "bevel"
    ) +
    ggplot2::scale_x_continuous(
        name = NULL,
        breaks = seq(1, 12, 3),
        minor_breaks = 1:12,
        labels = month.abb[seq(1, 12, 3)]
    ) +
    ggplot2::scale_color_viridis_d(
        name = NULL
    ) +
    ggplot2::facet_wrap(
        facets = ggplot2::vars(.data$Category),
        scales = "free_y"
    ) +
    ggplot2::theme_bw()
```

```{r}
#| label: look-at-time-distributions
#| dependson:
#| - load-violent-gun-crimes

VIOLENT_GUN_CRIMES |>
    dplyr::inner_join(
        nibrsr::GLOSSARY_OF_OFFENSE_TYPES,
        by = "offense_code"
    ) |>
    dplyr::filter(
        !is.na(.data$incident_date)
    ) |>
    dplyr::mutate(
        Year = lubridate::year(.data$incident_date),
        Category = .data$offense_category_name
    ) |>
    dplyr::count(
        .data$incident_id,
        .data$Year,
        .data$incident_hour,
        .data$Category
    ) |>
    dplyr::count(
        .data$Year,
        .data$incident_hour,
        .data$Category,
        name = "Frequency"
    ) |>
    ggplot2::ggplot(
        ggplot2::aes(
            x = .data$incident_hour,
            y = .data$Frequency,
            color = factor(.data$Year)
        )
    ) + 
    ggplot2::geom_line(
        linewidth = hiRx::PHI,
        lineend = "round",
        linejoin = "bevel"
    ) +
    ggplot2::scale_x_continuous(
        name = "Hour of Day",
        breaks = scales::breaks_width(6),
        minor_breaks = scales::breaks_width(1)
    ) +
    ggplot2::scale_y_continuous(
        name = "Number of incidents",
        limits = c(0, NA)
    ) +
    ggplot2::scale_color_viridis_d(
        name = NULL
    ) +
    ggplot2::facet_wrap(
        facets = ggplot2::vars(.data$Category),
        scales = "free_y"
    ) +
    ggplot2::theme_bw()
```

### Agencies in Wisconsin

```{r}
#| label: load-wi-agencies
#| dependson:
#| - identify-files

WI_AGENCIES <- TOC |>
    dplyr::filter(
        stringr::str_detect(.data$File, "WI")
    ) |>
    dplyr::select(
        "File", "Contents"
    ) |>
    purrr::pmap(\(File, Contents) nibrsr::extract_agencies(
        file.path(NIBRS_DIR, File),
        Contents
    )) |>
    purrr::list_rbind()

WI_AGENCIES |>
    dplyr::inner_join(
        nibrsr::GLOSSARY_OF_POPULATION_GROUPS,
        by = "population_group_code"
    ) |>
    dplyr::mutate(
        Code = .data$population_group_code |>
            stringr::str_extract("^\\d+") |>
            as.integer(),
        Flag = stringr::str_extract(.data$population_group_code, "\\D?$"),
        Suburban = dplyr::if_else(.data$suburban_area_flag,
                                  "Suburban",
                                  "Not suburban")
    ) |>
    dplyr::summarize(
        People = sum(.data$population, na.rm = TRUE),
        .by = c("Code", "Flag", "population_group_desc", "Suburban", "data_year")
    ) |>
    dplyr::summarize(
        People = .data$People |> median() |> scales::label_comma(accuracy = 1)(),
        .by = c("Code", "Flag", "population_group_desc", "Suburban")
    ) |>
    dplyr::arrange(
        .data$Code,
        .data$Flag
    ) |>
    dplyr::select(
        `Community Type` = "population_group_desc",
        "Suburban",
        "People"
    ) |>
    tidyr::pivot_wider(
        names_from = "Suburban",
        values_from = "People",
        values_fill = "-"
    ) |>
    knitr::kable(
        align = "lrr"
    )
```

```{r}
#| label: define-racine-agencies
#| dependson:
#| - load-wi-agencies

RACINE_AGENCIES <- tibble::tribble(
    ~ agency_id,	~ Name,	                     ~ Municipality,   ~ Place,
         21194L,	"Burlington PD",	         "Burlington",     "West of I-94",
         21195L,	"Racine PD",	             "Racine",         "City",
         21196L,	"Caledonia PD",	             "Caledonia",      "Suburbs",
         21200L,	"Mount Pleasant Village PD", "Mount Pleasant", "Suburbs",
         21201L,	"Sturtevant Village PD",     "Sturtevant",     "Suburbs",
         27657L,	"Wind Point PD",	         "Wind Point",     "Suburbs",
         28556L,	"Waterford PD",	             "Waterford Town", "West of I-94",
         21193L,	"Racine Co Sheriff",         "Racine",         "West of I-94"        
)

WI_PLACES <- WI_AGENCIES |>
    dplyr::left_join(RACINE_AGENCIES,
                     by = "agency_id") |>
    dplyr::mutate(
        Place = dplyr::coalesce(.data$Place,
                                "Wisconsin")
    ) |>
    dplyr::summarize(
        People = sum(.data$population, na.rm = TRUE),
        .by = c("Place", "data_year")
    )

WI_PLACES |>
    dplyr::arrange(
        .data$data_year,
        .data$Place
    ) |>
    tidyr::pivot_wider(
        names_from = "data_year",
        values_from = "People",
        values_fill = 0L
    ) |>
    knitr::kable()
```

### Compare Racine to other places

```{r}
#| label: compare-racine
#| dependson: 
#| - load-violent-gun-crimes
#| - load-wi-agencies
#| - define-racine-agencies

gun_violence_by_place <- VIOLENT_GUN_CRIMES |>
    dplyr::left_join(
        RACINE_AGENCIES,
        by = "agency_id"
    ) |>
    dplyr::mutate(
        Place = dplyr::coalesce(.data$Place,
                                "Wisconsin")
    ) |>
    dplyr::count(
        Year = lubridate::year(.data$incident_date),
        .data$Place,
        name = "Number of Offenses"
    ) |>
    dplyr::inner_join(
        WI_PLACES,
        by = c(Year = "data_year", "Place")
    ) |>
    dplyr::mutate(
        `Rate per 100K` = .data$`Number of Offenses` * 1e5 / .data$People
    )

gun_violence_by_place |>
    dplyr::select(
        "Place",
        "Year",
        "Rate per 100K"
    ) |>
    tidyr::pivot_wider(
        names_from = "Place",
        values_from = "Rate per 100K"
    ) |>
    knitr::kable()

gun_violence_by_place |>
    ggplot2::ggplot(
        ggplot2::aes(x = .data$Year,
                     y = .data$`Rate per 100K`,
                     color = .data$Place)
    ) +
    ggplot2::geom_line(
        linewidth = hiRx::PHI,
        lineend = "round",
        linejoin = "round"
    ) +
    ggplot2::scale_x_continuous(
        name = NULL,
        breaks = scales::breaks_width(2),
        minor_breaks = scales::breaks_width(1),
    ) +
    ggplot2::scale_y_continuous(
        limits = c(0, NA)
    ) +
    ggplot2::scale_color_manual(
        values = c(
            City = hiRx::higher_ex_cols("Racine Blue"),
            Suburbs = hiRx::higher_ex_cols("Mount Pleasant Green"),
            `West of I-94` = hiRx::higher_ex_cols("Sturtevant Brown"),
            Wisconsin = "red"
        )
    ) +
    ggplot2::theme_minimal()
```
