## Copyright (C) 2025 by Higher Expectations for Racine County

GLOSSARY_OF_OFFENSE_CODES <- tibble::tribble(
    ~ Group, ~ Category,                                 ~ Offense,                                     ~ Code, ~ Against,     ~ `NCIC Code`,
    "A",     "Animal Cruelty",                           "Animal Cruelty",                              "720",  "Society",     c(7201L),
    "A",     "Arson",                                    "Arson",                                       "200",  "Property",    c(2001L:2009L, 2099L),
    "A",     "Assault Offenses",                         "Aggravated Assault",                          "13A",  "Person",      c(1301L:1312L, 1314L:1315L),
    "A",     "Assault Offenses",                         "Simple Assault",                              "13B",  "Person",      c(1313L),
    "A",     "Assault Offenses",                         "Intimidation",                                "13C",  "Person",      c(1316L, 5215L:5216L),
    "A",     "Bribery",                                  "Bribery",                                     "510",  "Property",    c(5101L:5113L, 5199L),
    "A",     "Burglary/Breaking & Entering",             "Burglary/Breaking & Entering",                "220",  "Property",    c(2201L:2205L, 2207L, 2299L),
    "A",     "Commerce Violations",                      "Import Violations",                           "58A",  "Society",     integer(),
    "A",     "Commerce Violations",                      "Export Violations",                           "58B",  "Society",     integer(),
    "A",     "Commerce Violations",                      "Federal Liquor Offenses",                     "61A",  "Society",     c(4101L:4104L, 4199L, 6103L),
    "A",     "Commerce Violations",                      "Federal Tobacco Offenses",                    "61B",  "Society",     c(6102L),
    "A",     "Commerce Violations",                      "Wildlife Trafficking",                        "620",  "Society",     integer(),
    "A",     "Counterfeiting/Forgery",                   "Counterfeiting/Forgery",                      "250",  "Property",    c(2501L:2507L, 2509L, 2510L, 2589L, 2599L),
    "A",     "Destruction/Damage/Vandalism of Property", "Destruction/Damage/Vandalism of Property",    "290",  "Property",    c(2901L:2906L, 2999L),
    "A",     "Drug/Narcotic Offenses",                   "Drug/Narcotic Violations",                    "35A",  "Society",     c(3501L:3505L, 3510L:3513L, 3520L:3523L, 3530L:3533L, 3540L:3543L, 3560L:3564L, 3570L:3573L, 3580L:3583L, 3599L),
    "A",     "Drug/Narcotic Offenses",                   "Drug Equipment Violations",                   "35B",  "Society",     c(3550L),
    "A",     "Embezzlement",                             "Embezzlement",                                "270",  "Property",    c(2701L:2705L, 2799L),
    "A",     "Espionage",                                "Espionage",                                   "103",  "Society",     c(0103L),
    "A",     "Extortion/Blackmail",                      "Extortion/Blackmail",                         "210",  "Property",    c(2101L:2105L, 2199L),
    "A",     "Fraud Offenses",                           "False Pretenses/Swindle/Confidence Game",     "26A",  "Property",    c(2601L:2603L, 2607L, 2699L),
    "A",     "Fraud Offenses",                           "Credit Card/Automated Teller Machine Fraud",  "26B",  "Property",    c(2605L),
    "A",     "Fraud Offenses",                           "Impersonation",                               "26C",  "Property",    c(2604L),
    "A",     "Fraud Offenses",                           "Welfare Fraud",                               "26D",  "Property",    integer(),
    "A",     "Fraud Offenses",                           "Wire Fraud",                                  "26E",  "Property",    c(2608L),
    "A",     "Fraud Offenses",                           "Identity Theft",                              "26F",  "Property",    c(2610L),
    "A",     "Fraud Offenses",                           "Hacking/Computer Invasion",                   "26G",  "Property",    c(2609L),
    "A",     "Fraud Offenses",                           "Money Laundering",                            "26H",  "Society",     c(6300L),
    "A",     "Fugitive Offenses",                        "Harboring Escapee/Concealing from Arrest",    "49A",  "Society",     c(4904L, 4901L),
    "A",     "Fugitive Offenses",                        "Flight to Avoid Prosecution",                 "49B",  "Society",     c(4902L),
    "A",     "Fugitive Offenses",                        "Flight to Avoid Deportation",                 "49C",  "Society",     c(4902L),
    "A",     "Gambling Offenses",                        "Betting/Wagering",                            "39A",  "Society",     integer(),
    "A",     "Gambling Offenses",                        "Operating/Promoting/Assisting Gambling",      "39B",  "Society",     c(3901L:3902L, 3904L:3905L, 3907L, 3915L:3916L, 3918L, 3920L:3921L),
    "A",     "Gambling Offenses",                        "Gambling Equipment Violations",               "39C",  "Society",     c(3908L:3914L),
    "A",     "Gambling Offenses",                        "Sports Tampering",                            "39D",  "Society",     c(3919L),
    "A",     "Homicide Offenses",                        "Murder and Nonnegligent Manslaughter",        "09A",  "Person",      c(0901L:0908L, 0911L:0912L),
    "A",     "Homicide Offenses",                        "Negligent Manslaughter",                      "09B",  "Person",      c(0910L),
    "A",     "Homicide Offenses",                        "Justifiable Homicide",                        "09C",  "Not a Crime", integer(),
    "A",     "Human Trafficking",                        "Human Trafficking, Commercial Sex Acts",      "64A",  "Person",      c(6411L),
    "A",     "Human Trafficking",                        "Human Trafficking, Involuntary Servitude",    "64B",  "Person",      c(6411L),
    "A",     "Immigration Violations",                   "Illegal Entry into the United States",        "30A",  "Society",     c(0301L),
    "A",     "Immigration Violations",                   "False Citizenship",                           "30B",  "Society",     c(0302L),
    "A",     "Immigration Violations",                   "Smuggling Aliens",                            "30C",  "Society",     c(0303L),
    "A",     "Immigration Violations",                   "Re-entry after Deportation",                  "30D",  "Society",     c(0399L),
    "A",     "Kidnapping/Abduction",                     "Kidnapping/Abduction",                        "100",  "Person",      c(1001L:1009L, 1099L),
    "A",     "Larceny/Theft Offenses",                   "Pocket-picking",                              "23A",  "Property",    c(2301L),
    "A",     "Larceny/Theft Offenses",                   "Purse-snatching",                             "23B",  "Property",    c(2302L),
    "A",     "Larceny/Theft Offenses",                   "Shoplifting",                                 "23C",  "Property",    c(2303L),
    "A",     "Larceny/Theft Offenses",                   "Theft From Building",                         "23D",  "Property",    c(2308L, 2311L),
    "A",     "Larceny/Theft Offenses",                   "Theft From Coin-Operated Machine or Device",  "23E",  "Property",    c(2307L),
    "A",     "Larceny/Theft Offenses",                   "Theft From Motor Vehicle",                    "23F",  "Property",    c(2305L),
    "A",     "Larceny/Theft Offenses",                   "Theft of Motor Vehicle Parts or Accessories", "23G",  "Property",    c(2304L, 2407L),
    "A",     "Larceny/Theft Offenses",                   "All Other Larceny",                           "23H",  "Property",    c(2306L, 2309L:2310L, 2312L:2316L, 2410L),
    "A",     "Motor Vehicle Theft",                      "Motor Vehicle Theft",                         "240",  "Property",    c(2401L:2405L, 2408L, 2412L, 2499L),
    "A",     "Pornography/Obscene Material",             "Pornography/Obscene Material",                "370",  "Society",     c(3700L:3706L, 3799L),
    "A",     "Prostitution Offenses",                    "Prostitution",                                "40A",  "Society",     c(4003L:4004L),
    "A",     "Prostitution Offenses",                    "Assisting or Promoting Prostitution",         "40B",  "Society",     c(4001L:4002L, 4006L, 4007L, 4008L, 4009L, 4099L),
    "A",     "Prostitution Offenses",                    "Purchasing Prostitution",                     "40C",  "Society",     c(4005L),
    "A",     "Robbery",                                  "Robbery",                                     "120",  "Property",    c(1201L:1211L, 1299L),
    "A",     "Sex Offenses",                             "Rape",                                        "11A",  "Person",      c(1101L:1103L),
    "A",     "Sex Offenses",                             "Sodomy",                                      "11B",  "Person",      c(1104L:1115L),
    "A",     "Sex Offenses",                             "Sexual Assault With An Object",               "11C",  "Person",      integer(),
    "A",     "Sex Offenses",                             "Criminal Sexual Contact",                     "11D",  "Person",      c(3601L),
    "A",     "Sex Offenses",                             "Incest",                                      "36A",  "Person",      c(3604L, 3607L),
    "A",     "Sex Offenses",                             "Statutory Rape",                              "36B",  "Person",      c(1116L),
    "A",     "Sex Offenses",                             "Failure to Register as a Sex Offender",       "360",  "Society",     c(3612L),
    "A",     "Stolen Property Offenses",                 "Stolen Property Offenses",                    "280",  "Property",    c(2801L:2805L, 2899L),
    "A",     "Treason",                                  "Treason",                                     "101",  "Society",     c(0101L),
    "A",     "Weapon Law Violations",                    "Weapon Law Violations",                       "520",  "Society",     c(5201L:5214L, 5299L),
    "A",     "Weapon Law Violations",                    "Violation of National Firearm Act of 1934",   "521",  "Society",     integer(),
    "A",     "Weapon Law Violations",                    "Weapons of Mass Destruction",                 "522",  "Society",     integer(),
    "A",     "Weapon Law Violations",                    "Explosives",                                  "526",  "Society",     c(5204L:5206L, 5211L),
    "B",     "All Other Offenses",                       "All Other Offenses",                          "90Z",   NA,           NA,
    "B",     "Bond Default",                             "Failure to Appear",                           "90K",   "Society",    c(5015L),
    "B",     "Curfew/Loitering/Vagrancy Violations",     "Curfew/Loitering/Vagrancy Violations",        "90B",   "Society",    integer(),
    "B",     "Disorderly Conduct",                       "Disorderly Conduct",                          "90C",   "Society",    c(5310L:5311L, 5399L),
    "B",     "Driving Under the Influence",              "Driving Under the Influence",                 "90D",   "Society",    c(5403L:5404L),
    "B",     "Family Offenses, Nonviolent",              "Family Offenses, Nonviolent",                 "90F",   "Society",    c(3801L:3803L, 3806L:3808L, 3899L),
    "B",     "Federal Resource Violation",               "Federal Resource Violations",                 "90L",   "Society",    integer(),
    "B",     "Liquor Law Violations",                    "Liquor Law Violations",                       "90G",   "Society",    c(4101L:4104L, 4199L),
    "B",     "Perjury",                                  "Perjury",                                     "90M",   "Society",    c(5003L, 5004L),
    "B",     "Trespass of Real Property",                "Trespass of Real Property",                   "90J",   "Property",   c(5707L)
)

usethis::use_data(GLOSSARY_OF_OFFENSE_CODES, overwrite = TRUE)
