## Copyright (C) 2025 by Higher Expectations for Racine County

extract_agencies <- function(.archive_path, .contents = NULL) {
    if (is.null(.contents)) {
        .contents <- zip::zip_list(.archive_path)
    }
    extract_archived_csv(
        .archive_path,
        stringr::str_subset(.contents$filename,
                            "agencies\\.csv"),
        list(
            YEARLY_AGENCY_ID = "i",
            AGENCY_ID = "i",
            DATA_YEAR = "i",
            ORI = "c",
            LEGACY_ORI = "c",
            COVERED_BY_LEGACY_ORI = "l",
            DIRECT_CONTRIBUTOR_FLAG = "c",
            DORMANT_FLAG = "c",
            DORMANT_YEAR = "c",
            REPORTING_TYPE = "c",
            UCR_AGENCY_NAME = "c",
            NCIC_AGENCY_NAME = "c",
            PUB_AGENCY_NAME = "c",
            PUB_AGENCY_UNIT = "c",
            AGENCY_STATUS = "c",
            STATE_ID = "i",
            STATE_NAME = "c",
            STATE_ABBR = "c",
            STATE_POSTAL_ABBR = "c",
            DIVISION_CODE = "i",
            DIVISION_NAME = "c",
            REGION_CODE = "i",
            REGION_NAME = "c",
            REGION_DESC = "c",
            AGENCY_TYPE_NAME = "c",
            POPULATION = "n",
            SUBMITTING_AGENCY_ID = "i",
            SAI = "c",
            SUBMITTING_AGENCY_NAME = "c",
            SUBURBAN_AREA_FLAG = "c",
            POPULATION_GROUP_ID = "i",
            POPULATION_GROUP_CODE = "c",
            POPULATION_GROUP_DESC = "c",
            PARENT_POP_GROUP_CODE = "i",
            PARENT_POP_GROUP_DESC = "c",
            MIP_FLAG = "c",
            POP_SORT_ORDER = "n",
            SUMMARY_RAPE_DEF = "c",
            PE_REPORTED_FLAG = "c",
            MALE_OFFICER = "n",
            MALE_CIVILIAN = "n",
            `PED.MALE_OFFICER+PED.MALE_CIVILIAN` = "n",
            FEMALE_OFFICER = "n",
            FEMALE_CIVILIAN = "n",
            `PED.FEMALE_CIVILIAN+PED.FEMALE_OFFICER` = "n",
            NIBRS_CERT_DATE = "c",
            NIBRS_START_DATE = "c",
            NIBRS_LEOKA_START_DATE = "c",
            NIBRS_CT_START_DATE = "c",
            NIBRS_MULTI_BIAS_START_DATE = "c",
            NIBRS_OFF_ETH_START_DATE = "c",
            COVERED_FLAG = "c",
            COUNTY_NAME = "c",
            MSA_NAME = "c",
            PUBLISHABLE_FLAG = "c",
            PARTICIPATED = "c",
            NIBRS_PARTICIPATED = "c",
            .default = "-"
        )
    )
}
